import 'package:flutter/material.dart';
import 'main.dart';

/// Fluxo de clientes reconstruído a partir da referência visual do CobrApp.
class OriginalCustomerFlow extends StatefulWidget {
  const OriginalCustomerFlow({super.key});
  @override State<OriginalCustomerFlow> createState()=>_OriginalCustomerFlowState();
}
class _OriginalCustomerFlowState extends State<OriginalCustomerFlow>{
  List<Map<String,dynamic>> customers=[],loans=[]; bool loading=true,searching=false; String q='',filter='Todos';
  @override void initState(){super.initState();load();}
  Future<void> load()async{try{final r=await Future.wait([rpc('cobrapp_app_list_customers'),rpc('cobrapp_app_list_loans')]);if(!mounted)return;setState((){customers=(r[0]as List).map((e)=>Map<String,dynamic>.from(e as Map)).toList();loans=(r[1]as List).map((e)=>Map<String,dynamic>.from(e as Map)).toList();loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
  int count(Map<String,dynamic>c)=>loans.where((l)=>l['customer_id']?.toString()==c['id']?.toString()).length;
  @override Widget build(BuildContext context){final list=customers.where((c)=>'${c['name']} ${c['document']} ${c['phone']}'.toLowerCase().contains(q.toLowerCase())).toList();return Scaffold(backgroundColor:bg,body:RefreshIndicator(onRefresh:load,child:ListView(padding:EdgeInsets.zero,children:[WaveHeader(title:'Clientes (${customers.length})',actions:[hi(Icons.search,()=>setState(()=>searching=!searching)),hi(Icons.route_outlined,(){}),hi(Icons.sell_outlined,(){}),hi(Icons.sort,(){}),hi(Icons.more_vert,(){})]),Padding(padding:const EdgeInsets.fromLTRB(14,0,14,110),child:Column(children:[if(searching)...[TextField(autofocus:true,onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(hintText:'Buscar cliente',prefixIcon:Icon(Icons.search))),const SizedBox(height:10)],SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:['Todos','Pago hoje','Pagam hoje','Com crédito'].map((x)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_)=>setState(()=>filter=x)))).toList())),if(loading)const LinearProgressIndicator(),for(final c in list)card(c),const SizedBox(height:16),SizedBox(width:260,height:56,child:FilledButton.icon(onPressed:()=>openPage(context,'Adicionar cliente',const CreateCustomerPage()),icon:const Icon(Icons.person_add_alt_1),label:const Text('Adicionar cliente',style:TextStyle(fontWeight:FontWeight.w900))))]))])),floatingActionButton:FloatingActionButton(backgroundColor:const Color(0xFF193D34),foregroundColor:mint,onPressed:()=>openPage(context,'Calculadora',const CalculatorPage()),child:const Icon(Icons.calculate_outlined)));}
  Widget hi(IconData i,VoidCallback f)=>IconButton(onPressed:f,icon:Icon(i,color:Colors.white));
  Widget card(Map<String,dynamic>c){final n=(c['name']??'Cliente').toString();return Container(margin:const EdgeInsets.only(top:10),decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(21),border:Border.all(color:const Color(0xFF355A4E)),boxShadow:const[BoxShadow(color:Color(0x332FC89A),blurRadius:13)]),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:15,vertical:7),leading:CircleAvatar(radius:24,backgroundColor:mintDark,child:Text(n.isEmpty?'?':n[0].toUpperCase(),style:const TextStyle(fontWeight:FontWeight.w900))),title:Text(n,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((c['document']??'Sem identificação').toString(),style:const TextStyle(color:muted)),const SizedBox(height:4),const Text('Não alocado',style:TextStyle(fontSize:11,color:Colors.white60))]),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Container(padding:const EdgeInsets.all(7),decoration:BoxDecoration(color:const Color(0xFF173D54),borderRadius:BorderRadius.circular(12)),child:Text('${count(c)}')),const Icon(Icons.chevron_right)]),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OriginalCustomerDetail(customer:c,allLoans:loans))));}
}
class OriginalCustomerDetail extends StatefulWidget{const OriginalCustomerDetail({super.key,required this.customer,required this.allLoans});final Map<String,dynamic>customer;final List<Map<String,dynamic>>allLoans;@override State<OriginalCustomerDetail>createState()=>_OriginalCustomerDetailState();}
class _OriginalCustomerDetailState extends State<OriginalCustomerDetail>{late List<Map<String,dynamic>> loans;@override void initState(){super.initState();loans=widget.allLoans.where((l)=>l['customer_id']?.toString()==widget.customer['id']?.toString()).toList();}@override Widget build(BuildContext context){final n=(widget.customer['name']??'Cliente').toString();return Scaffold(backgroundColor:bg,body:ListView(padding:EdgeInsets.zero,children:[WaveHeader(title:n,actions:[IconButton(onPressed:(){},icon:const Icon(Icons.more_vert))]),Padding(padding:const EdgeInsets.fromLTRB(14,0,14,100),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[CircleAvatar(radius:27,backgroundColor:mintDark,child:Text(n.isEmpty?'?':n[0].toUpperCase())),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text((widget.customer['document']??'').toString(),style:const TextStyle(color:muted))]))]),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>openPage(context,'Novo Empréstimo',CreateLoanPage(initialCustomerId:widget.customer['id']?.toString())),icon:const Icon(Icons.add_card),label:const Text('Novo Empréstimo'))),const SizedBox(height:18),const Text('Empréstimos',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),if(loans.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(22),child:Center(child:Text('Nenhum empréstimo para este cliente')))),for(final l in loans)Card(child:ListTile(leading:const CircleAvatar(backgroundColor:mintDark,child:Icon(Icons.account_balance_wallet_outlined)),title:Text(money(toDouble(l['amount']??l['principal'])),style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),subtitle:Text('${l['payment_frequency']??'Mensal'} • ${statusPt(l['status'])}'),trailing:PopupMenuButton<String>(itemBuilder:(_)=>const[PopupMenuItem(value:'open',child:Text('Abrir crédito')),PopupMenuItem(value:'pay',child:Text('Pagar'))],onSelected:(x){if(x=='open')openPage(context,n,LoanDetail(loanId:l['id'].toString()));else Navigator.push(context,MaterialPageRoute(builder:(_)=>OriginalPaymentPage(loan:l)));})))]))]));}}
class OriginalPaymentPage extends StatefulWidget{const OriginalPaymentPage({super.key,required this.loan});final Map<String,dynamic>loan;@override State<OriginalPaymentPage>createState()=>_OriginalPaymentPageState();}
class _OriginalPaymentPageState extends State<OriginalPaymentPage>{final value=TextEditingController();int qty=1;String method='Dinheiro',apply='Juros e Principal';bool share=true;@override Widget build(BuildContext context){final parcel=toDouble(widget.loan['installment_amount']??widget.loan['amount']);final debt=toDouble(widget.loan['total_debt']??widget.loan['amount']);return Scaffold(backgroundColor:bg,appBar:AppBar(backgroundColor:bg,title:Text((widget.loan['customer_name']??'Cliente').toString())),body:ListView(padding:const EdgeInsets.all(14),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Adicionar Empréstimo',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),arow('Valor da Parcela',money(parcel),true),arow('Somente Juros',money(toDouble(widget.loan['interest_amount'])),false),arow('Dívida Total',money(debt),false),TextField(controller:value,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Valor',prefixIcon:Icon(Icons.attach_money))),const SizedBox(height:16),const Text('Resumo do Pagamento',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Juros: R$ 0,00     Principal: R$ 0,00'),const SizedBox(height:14),DropdownButtonFormField<String>(value:apply,decoration:const InputDecoration(labelText:'Aplicar o pagamento a*'),items:['Juros e Principal','Somente Juros','Somente Principal'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>apply=x!)),const SizedBox(height:10),DropdownButtonFormField<String>(value:method,decoration:const InputDecoration(labelText:'Método de Pagamento'),items:['Dinheiro','Pix','Cartão','Transferência'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>method=x!)),const SizedBox(height:10),const InputDecorator(decoration:InputDecoration(labelText:'Data do Pagamento',suffixIcon:Icon(Icons.calendar_month)),child:Text('Hoje')),const SizedBox(height:10),const TextField(maxLines:2,decoration:InputDecoration(labelText:'Adicionar Nota')),CheckboxListTile(contentPadding:EdgeInsets.zero,value:share,onChanged:(x)=>setState(()=>share=x??false),title:const Text('Você deseja imprimir ou compartilhar?')),SizedBox(width:double.infinity,height:56,child:FilledButton.icon(onPressed:(){},icon:const Icon(Icons.monetization_on_outlined),label:const Text('GUARDE O PAGAMENTO',style:TextStyle(fontWeight:FontWeight.w900))))])))]));}
Widget arow(String l,String a,bool step)=>Padding(padding:const EdgeInsets.symmetric(vertical:10),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l,style:const TextStyle(color:muted)),Text(a,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900))])),if(step)Row(children:[IconButton(onPressed:qty>1?()=>setState(()=>qty--):null,icon:const Icon(Icons.remove)),Text('$qty'),IconButton(onPressed:()=>setState(()=>qty++),icon:const Icon(Icons.add))])else IconButton.filledTonal(onPressed:()=>value.text=a.replaceAll(RegExp(r'[^0-9,]'),''),icon:const Icon(Icons.add))]));}
